USE master

INSERT INTO tb2A (rmAluno, nomeAluno, statusAluno)
VALUES 
	(1,'Guilherme de oliveira Machado', 'APROVADO'),
	(2,'GIOVANNA EDUARDA DASMASCENO REIS', 'APROVADO'),
	(3,'HENRIQUE SILVA FERNANDO', 'APROVADO'),
	(4,'JOÃO MARCOS', 'REPROVADO'),
	(5,'MAURICIO GOMES', 'REPROVADO'),
	(6,'PEDRO PASCHOAL', 'REPROVADO'),
	(7,'PAULA APARECIDA', 'APROVADO'),
	(8,'VITORIA BARROSO', 'APROVADO'),
	(9,'GABRIELLE BRILHANTE', 'APROVADO'),
	(10,'KAUANE DE SOUZA BRITO', 'APROVADO')


INSERT INTO tb2B (rmAluno, nomeAluno, statusAluno)
VALUES 

	(1,'RAFAELLA MENDONÇA', 'APROVADO'),
	(2,'DANIEL LOPES', 'REPROVADO'),
	(3,'ANA BEATRIZ', 'REPROVADO'),
	(4,'ANDRÉ AUGUSTO', 'REPROVADO'),
	(5,'ANTONIO AUGUSUTO', 'APROVADO'),
	(6,'MARIANA BRITO', 'APROVADO'),
	(7,'DIEGO ROCHA', 'APROVADO'),
	(8,'CAIO RIBEIRO', 'APROVADO'),
	(9,'REBECCA MANUELA DA SILVA', 'APROVADO'),
	(10,'VICTOR VOLP', 'APROVADO')

